#
#	This field is used to discriminate different instances in syslog
#
Id		= "default"

#
#	List of IPv4 and IPv6 to listen to
#
Listen		= [ "127.0.0.1", "::1" ]

#
#	This field contain the URL of the server nataraja will forward to
#
Proxied		= "http://host.tld/"

#
#	Path to the directory containing the vhosts
#
#	The path must already exists before running nataraja
IncludeVhosts	= "/path/to/vhosts"


#
#	Path to an alternative /dev/log like socket
#
#	The socket must already exists before running nataraja
DevLog		= "/dev/log"


#
#	Time to wait before the next OCSP verification
#
#	not less than 5m
#	not more than 1d
RefreshOCSP	= "1h"

#
#	this is the secret shared between several redondant proxy
#	to cope with TLS session ticket
#
#	if the string is empty, io.Rand will feed it but
#	in case of restart, all the previous session will be invalidated
TicketMasterSecret	= "some secret string"
